apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-db-config
  labels:
    app: drone-db
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: drone-db
spec:
  serviceName: drone-db
  selector:
    matchLabels:
      app: drone-db
  replicas: 1
  template:
    metadata:
      labels:
        app: drone-db
    spec:
      containers:
        - name: drone-db
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: drone-db-config
---
apiVersion: v1
kind: Service
metadata:
  name: drone-db
  labels:
    app: drone-db
spec:
  selector:
    app: drone-db
  ports:
    - protocol: TCP
      name: postgres
      port: 5432
      targetPort: 5432
