name: Docker Image CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build Frontend
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: jibril101/frontend
        dockerfile: ./FrontendApplication/Dockerfile
        directory: ./FrontendApplication
        tags: latest
        registry: quay.io
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    
    - name: Build Quote Service
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: jibril101/quote-service
        dockerfile: ./QuoteService/Dockerfile
        directory: ./QuoteService
        tags: latest
        registry: quay.io
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    
    - name: Build Gateway Service
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: jibril101/gateway
        dockerfile: ./ApiGateway/Dockerfile
        directory: ./ApiGateway
        tags: latest
        registry: quay.io
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    


        
