name: Docker Image CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: cloudshaykh
  GKE_ZONE: us-west2-a

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: run npm 
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: run npm install
      working-directory: ./FrontendApplication
      run: npm install

    - name: run npm build
      working-directory: ./FrontendApplication
      run: npm run build

    - name: Build Frontend Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: jibril101/frontend
        dockerfile: ./FrontendApplication/Dockerfile
        directory: ./FrontendApplication
        tags: $GITHUB_SHA
        registry: quay.io
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    
    - name: Build Quote Service
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: jibril101/quote-service
        dockerfile: ./QuoteService/Dockerfile
        directory: ./QuoteService
        tags: $GITHUB_SHA
        registry: quay.io
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    
    - name: Build Gateway Service
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: jibril101/gateway
        dockerfile: ./ApiGateway/Dockerfile
        directory: ./ApiGateway
        tags: $GITHUB_SHA
        registry: quay.io
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

     # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}
    
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: Deploy
      run: |-
        ./kustomize edit set image quay.io/jibril101/frontend:$GITHUB_SHA
        ./kustomize edit set image quay.io/jibril101/gateway:$GITHUB_SHA
        ./kustomize edit set image quay.io/jibril101/quote-service:$GITHUB_SHA
        ./kustomize build . | kubectl apply -f - 
        kubectl rollout status deployment/frontend
        kubectl rollout status deployment/quote-service
        kubectl rollout status deployment/gateway